name: Deploy to Cloudflare

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Download Build Artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: build-artifact
      #     path: dist

      - name: Deploy to Cloudflare
        run:  npm run && wrangler pages deploy ./dist
      # - name: Deploy to Cloudflare
        # uses: cloudflare/wrangler-action@v3
        # with:
          # apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        # env:
          # WORKING_DIRECTORY: './dist'